version: '3'
services: 

    api:
        build: 
            context: ./
        container_name: node-mongo-jwt
        restart: always
        command: npm start
        ports: 
            - "3000:3000"
        links: 
            - mongo

    mongo:
        image: mongo
        container_name: mongo-node
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secure
        ports:
            - 27018:27017
        volumes:
            # - /Users/thanachantrapong/mongodb/data/db2:/data/db
            -  /docker/data/db:/data/db
